import {
  Landmark,
  Building2,
  Mountain,
  Zap,
  Fuel,
  Wheat,
  Factory,
  Truck,
  Cpu,
  HeartPulse,
  Hotel,
  Store,
  HandHeart,
  ShieldCheck,
  Gem,
  Lightbulb,
  Scale,
  Users,
  Leaf,
  GraduationCap,
  UsersRound,
  HeartHandshake,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  landmark: Landmark,
  "building-2": Building2,
  mountain: Mountain,
  zap: Zap,
  fuel: Fuel,
  wheat: Wheat,
  factory: Factory,
  truck: Truck,
  cpu: Cpu,
  "heart-pulse": HeartPulse,
  hotel: Hotel,
  store: Store,
  "hand-heart": HandHeart,
  "shield-check": ShieldCheck,
  gem: Gem,
  lightbulb: Lightbulb,
  scale: Scale,
  users: Users,
  leaf: Leaf,
  "graduation-cap": GraduationCap,
  "users-round": UsersRound,
  "heart-handshake": HeartHandshake,
};

export const DEFAULT_ICON = Gem;
